# Render.com Deployment Configuration
# Deploy backend to Render.com

services:
  - type: web
    name: vastu-backend
    env: node
    plan: standard
    
    # Build Configuration
    buildCommand: npm install && npm run build
    startCommand: npm start
    
    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 3000
      
      # Database - MongoDB Atlas
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      
      - key: DATABASE_NAME
        value: vastu_db
      
      - key: DB_MAX_POOL_SIZE
        value: 20
      
      - key: DB_MIN_POOL_SIZE
        value: 5
      
      - key: DB_MAX_IDLE_TIME_MS
        value: 60000
      
      # JWT Secrets - Set in Render dashboard
      - key: JWT_SECRET
        sync: false
      
      - key: JWT_REFRESH_SECRET
        sync: false
      
      - key: JWT_EXPIRY
        value: 24h
      
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      
      # CORS Configuration
      - key: CORS_ORIGIN
        value: https://yourdomain.com,https://www.yourdomain.com,https://vastu-frontend.vercel.app
      
      - key: FRONTEND_URL
        value: https://yourdomain.com
      
      # Logging
      - key: LOG_LEVEL
        value: info
      
      # Admin Credentials - Change immediately after first login
      - key: ADMIN_EMAIL
        value: admin@yourdomain.com
      
      - key: ADMIN_PASSWORD
        sync: false  # Set in Render dashboard
      
      # Commission Settings
      - key: DEFAULT_COMMISSION_TYPE
        value: PERCENTAGE
      
      - key: DEFAULT_COMMISSION_VALUE
        value: 10
      
      - key: DEFAULT_GST_PERCENTAGE
        value: 18
      
      - key: DEFAULT_EXCLUDE_GST_FROM_BASE
        value: false
      
      # Referral System
      - key: REFERRAL_CODE_PREFIX
        value: BA
      
      - key: REFERRAL_CODE_LENGTH
        value: 12
      
      # File Upload
      - key: MAX_FILE_SIZE
        value: 5242880
    
    # Health Check
    healthCheckPath: /health
    healthCheckInterval: 30
    
    # Scaling
    numInstances: 1
    
    # Disk
    disk:
      name: logs
      mountPath: /app/logs
      sizeGB: 1
    
    # Cron Jobs (optional)
    # cronJobs:
    #   - name: backup-database
    #     schedule: "0 2 * * *"  # Daily at 2 AM
    #     command: npm run backup:db

# Databases (if using Render's managed database)
# databases:
#   - name: vastu-db
#     databaseName: vastu_db
#     user: vastu_user
#     plan: standard
#     version: "6.0"  # MongoDB version
#     region: oregon  # Change to your preferred region
#     ipAllowList:
#       - address: 0.0.0.0/0  # Allow all IPs (restrict in production)

